export default {
  'Aldrich-Regular': require('./Aldrich-Regular.ttf'),
  'Barlow-Black': require('./Barlow-Black.ttf'),
  'Barlow-BlackItalic': require('./Barlow-BlackItalic.ttf'),
  'Barlow-Bold': require('./Barlow-Bold.ttf'),
  'Barlow-BoldItalic': require('./Barlow-BoldItalic.ttf'),
  'Barlow-ExtraBold': require('./Barlow-ExtraBold.ttf'),
  'Barlow-ExtraBoldItalic': require('./Barlow-ExtraBoldItalic.ttf'),
  'Barlow-ExtraLightItalic': require('./Barlow-ExtraLightItalic.ttf'),
  'Barlow-ExtraLight': require('./Barlow-ExtraLight.ttf'),
  'Barlow-Italic': require('./Barlow-Italic.ttf'),
  'Barlow-Light': require('./Barlow-Light.ttf'),
  'Barlow-LightItalic': require('./Barlow-LightItalic.ttf'),
  'Barlow-Medium': require('./Barlow-Medium.ttf'),
  'Barlow-MediumItalic': require('./Barlow-MediumItalic.ttf'),
  'Barlow-Regular': require('./Barlow-Regular.ttf'),
  'Barlow-SemiBold': require('./Barlow-SemiBoldItalic.ttf'),
  'Barlow-SemiBoldItalic': require('./Barlow-SemiBoldItalic.ttf'),
  'Barlow-Thin': require('./Barlow-Thin.ttf'),
  'Barlow-ThinItalic': require('./Barlow-ThinItalic.ttf'),
};
