name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - dev

jobs:
  test-mobile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn

      - name: Install expo CLI
        run: yarn add --global eas-cli
        
      - name: Test the app
        run: yarn test

      - name: Build the app
        if: success() && github.ref == 'refs/heads/main'
        run: |
          eas login -u ${{ secrets.EXPO_USERNAME }} -p ${{ secrets.EXPO_PASSWORD }}
          eas build --platform android
